### ISSUE TITLE
Do any logo

### ISSUE THREAD

**Issue by skatkov** [skatkov/carriage#15]

**Comment by KirillSokur** [comment]
I made a very raw mockup of logo ideas. please give your feedback.

![image](https://user-images.githubusercontent.com/13163708/74417309-10516300-4e79-11ea-99d0-56f299efe7b4.png)

<hr>

![image](https://user-images.githubusercontent.com/13163708/74417342-1d6e5200-4e79-11ea-9daa-cfa1bb0b4b8f.png)


<hr>

![image](https://user-images.githubusercontent.com/13163708/74417351-23643300-4e79-11ea-9842-11b5531e5ecc.png)
